// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWiLnQSDFPE348-7PsHGcF-qPaAUXMWYg',
    appId: '1:40887549835:web:ecef433414e003cb2a798e',
    messagingSenderId: '40887549835',
    projectId: 'livra-efb01',
    authDomain: 'livra-efb01.firebaseapp.com',
    storageBucket: 'livra-efb01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQZ_M4GIqGEztKdZlGoHOvIjET6GWKLU',
    appId: '1:40887549835:android:dc2a9c07bdc9ea3f2a798e',
    messagingSenderId: '40887549835',
    projectId: 'livra-efb01',
    storageBucket: 'livra-efb01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBteWRk1HroxSt72lOET5-tZZDL8L_u1mA',
    appId: '1:40887549835:ios:8ec9e9e4da52f7432a798e',
    messagingSenderId: '40887549835',
    projectId: 'livra-efb01',
    storageBucket: 'livra-efb01.firebasestorage.app',
    iosClientId: '40887549835-quvj8c34ra64nmg5q2it8s5rqdfjac05.apps.googleusercontent.com',
    iosBundleId: 'com.example.livra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBteWRk1HroxSt72lOET5-tZZDL8L_u1mA',
    appId: '1:40887549835:ios:8ec9e9e4da52f7432a798e',
    messagingSenderId: '40887549835',
    projectId: 'livra-efb01',
    storageBucket: 'livra-efb01.firebasestorage.app',
    iosClientId: '40887549835-quvj8c34ra64nmg5q2it8s5rqdfjac05.apps.googleusercontent.com',
    iosBundleId: 'com.example.livra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWiLnQSDFPE348-7PsHGcF-qPaAUXMWYg',
    appId: '1:40887549835:web:c5ce95eb12ac48762a798e',
    messagingSenderId: '40887549835',
    projectId: 'livra-efb01',
    authDomain: 'livra-efb01.firebaseapp.com',
    storageBucket: 'livra-efb01.firebasestorage.app',
  );
}
